### ISSUE TITLE
Not compatible with Thunderbird 68.7.0

### ISSUE THREAD

**Issue by remissao** [mi-yo/thunderbird-subjectcleaner#11]
Please fix compatibility with the latest version.

The debug says the addon is missing the manifest.json file.

**Comment by whistler-mb** [comment]
Are you using the branch "feature/tb68" ?

There is an manifest.json

**Comment by inkarkat** [comment]
It would be super great if you could publish a new release that works with Thunderbird 68; that would make it really easy for us unwashed masses (that don't understand anything about building the add-on) to continue to use this useful add-on. Thanks!

**Comment by whistler-mb** [comment]
I only tested it with linux, but it should on other platforms too.

After downloading you have to rename it from zip to xpi. Then you can install it manually in thunderbird.
[subject_cleaner-1.4.1-tb.zip](https://github.com/mi-yo/thunderbird-subjectcleaner/files/4516680/subject_cleaner-1.4.1-tb.zip)

**Comment by mi-yo** [comment]
I have published new ver.2.0.0.
It will be published officially as soon as Mozilla review is completed.

**Comment by mi-yo** [comment]
Ver.2.0.0 has been published officially.
Regards

**Comment by inkarkat** [comment]
Great! Thanks to both @whistler-mb and @mi-yo for providing the preliminary and final release; both have been working fine for me. I think this issue can now be closed.

**Comment by tessus** [comment]
Unfortunately, there is no way to configure the add-on.

The `Tools -> Add-on Preferences` is empty.

**Comment by inkarkat** [comment]
@tessus Not for me. I have an entry there, pointing to `chrome://subjectcleaner/content/options.xul`. Thunderbird 68.7.0 (64-bit) on Ubuntu 16.04 LTS.

**Comment by tessus** [comment]
I'm on macOS 10.15.4 and it's empty.

**Comment by mi-yo** [comment]
@tessus 
As you said that is empty.
But you can configure with `Hamburger menu (at TB window) -> Add-ons -> Subject Cleaner` .

<img width="952" alt="image" src="https://user-images.githubusercontent.com/6334777/80858917-c61d9800-8c97-11ea-901c-e020bf8a3de2.png">

**Comment by tessus** [comment]
@mi-yo thank you. this worked.
