### ISSUE TITLE
After subject cleaning, focus on body text field

### ISSUE THREAD

**Issue by orschiro** [mi-yo/thunderbird-subjectcleaner#2]
Hi @mi-yo,

I noticed that after cleaning the subject, the focus of the pointer remains on the subject field.

However, I find it more intuitive to put the focus on the body field, to immediately begin with writing a response.

What do you think?

Steps to reproduce:

1. Reply to an email in a new text window
2. You will notice that when beginning typing, you will add to the subject because the focus of the pointer is on the subject field instead of the body field.

Thanks for your reply!

**Comment by mi-yo** [comment]
Fixed in version 1.3.0 and published. Please try it.

**Comment by orschiro** [comment]
@mi-yo 

`1.3.0` jumps immediately to the body field. Very nice implementation, thanks!
