### ISSUE TITLE
Incompatible with Thunderbird 60.0

### ISSUE THREAD

**Issue by ExTechOp** [mi-yo/thunderbird-subjectcleaner#3]
This add-on was disabled with Thunderbird 60.0, how difficult would it be to make it work again?

**Comment by mi-yo** [comment]
Hi @ExTechOp,

I have activated version 60.* with this add-on.
Please try again if it works.

**Comment by sukhoi47** [comment]
ExTechOp is correct, it is not working on version 60 (or even version 45).
Seems @mi-yo changed the compatibility version at Thunderbird extensions website, but not inside the extension manifest file (install.rdf), where the max version is set to 31. 

>       <Description>
>         <em:id>{3550f703-e582-4d05-9a08-453d09bdfdc6}</em:id>
>         <em:minVersion>3.1</em:minVersion>
>         <em:maxVersion>**31.***</em:maxVersion>
>       </Description>

I changed the maxVersion myself, but seems it still is not working.

**Comment by mi-yo** [comment]
I have fixed it to work with Thunderbird 60.*.
There were few changes in MDN interface to read / write settings.
https://bugzilla.mozilla.org/show_bug.cgi?id=1414096
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefBranch#setComplexValue()

Release version 1.4.0 is under review at Mozilla.

**Comment by mi-yo** [comment]
1.4.0 has been released. Please try again.
https://addons.thunderbird.net/ja/thunderbird/addon/subject-cleaner/

**Comment by ExTechOp** [comment]
This version seems to work fine. Sorry for the long delay in answering.
