### ISSUE TITLE
Incompatible with Thunderbird 68.1.2

### ISSUE THREAD

**Issue by Explorare** [mi-yo/thunderbird-subjectcleaner#6]
Thanks.

**Comment by tooomm** [comment]
I'm looking forward to a compatible version as well.

This can be helpful @mi-yo: https://developer.thunderbird.net/add-ons/tb68

**Comment by mi-yo** [comment]
I am going to maintain compatibility with TB 68+. Please wait for a while.

**Comment by jondo** [comment]
In the meantime:
Part of this is also covered by the config setting `mailnews.localizedRe`, see https://blog.effenberger.org/2015/10/06/my-thunderbird-configuration-tweaking-the-settings/

**Comment by akira-ishizaki** [comment]
勝手に修正版作ったのでここにおいときました
I fixed for TB 68+.
https://drive.google.com/open?id=1Cxf7md47Ffd_LwfP808goJzA0zD9qzQg

**Comment by Explorare** [comment]
> 
> 
> 勝手に修正版作ったのでここにおいときました
> I fixed for TB 68+.
> https://drive.google.com/open?id=1Cxf7md47Ffd_LwfP808goJzA0zD9qzQg

有能ニキ助かる。有難うございました。🎉

**Comment by tooomm** [comment]
@Explorare Do you mind sending a pr with the fix to this projekt instead?

**Comment by Explorare** [comment]
@tooomm Got it. I'll send a PR tonight.

**Comment by jondo** [comment]
Can this issue please kept open s.t. subscribers get email notification when the new release is available for installation?

**Comment by Explorare** [comment]
> 
> 
> Can this issue please kept open s.t. subscribers get email notification when the new release is available for installation?


I think you would get the email notification when their is a new reply whether or not the issue was open.

**Comment by jondo** [comment]
Yes, but I can't be sure whether there will be such a reply :-)
Anyway, thanks to everyone involved!

**Comment by tooomm** [comment]
Also, an open issues is easier to find for people having the same issue/request.
